import Foundation
import Testing
@testable import MDReaderApp

private let memoryNote = [
    "---",
    "name: feedback-open-markdown-via-mdreader",
    "description: \"When the user wants to READ a markdown file\"",
    "metadata: ",
    "  node_type: memory",
    "  type: feedback",
    "---",
    "",
    "# Open markdown via mdreader",
].joined(separator: "\n")

private func properties(_ source: String) -> [String]? {
    FrontMatter.parse(lines: source.components(separatedBy: "\n"))?.entries.map { "\($0.key)=\($0.value)" }
}

@Test func parsesMemoryNoteFrontMatter() {
    let frontMatter = FrontMatter.parse(lines: memoryNote.components(separatedBy: "\n"))
    #expect(frontMatter == FrontMatter(entries: [
        .init(key: "name", value: "feedback-open-markdown-via-mdreader"),
        .init(key: "description", value: "When the user wants to READ a markdown file"),
        .init(key: "metadata.node_type", value: "memory"),
        .init(key: "metadata.type", value: "feedback"),
    ], closingLine: 6))
}

@Test func rendersMemoryNoteFrontMatterAsProperties() {
    let rendered = MarkdownRenderer.render(memoryNote)
    #expect(rendered.html == """
    <details class="frontmatter" data-line="0" open><summary>Properties</summary><table><tbody>
    <tr><th>name</th><td>feedback-open-markdown-via-mdreader</td></tr>
    <tr><th>description</th><td>When the user wants to READ a markdown file</td></tr>
    <tr><th>metadata.node_type</th><td>memory</td></tr>
    <tr><th>metadata.type</th><td>feedback</td></tr>
    </tbody></table></details>
    <h1 id="open-markdown-via-mdreader" data-line="8">Open markdown via mdreader</h1>

    """)
    #expect(rendered.outline == [OutlineItem(id: "open-markdown-via-mdreader", level: 1, title: "Open markdown via mdreader", line: 8)])
}

@Test func unquotesFrontMatterValues() {
    #expect(properties("---\ntitle: \"Q3: plan\"\nstatus: 'draft'\n---") == ["title=Q3: plan", "status=draft"])
}

@Test func joinsFrontMatterListItems() {
    let md = """
    ---
    tags:
      - qa
      - "swift"
    aliases:
    - Kickoff
    - 'Project Start'
    ---
    """
    #expect(properties(md) == ["tags=qa, swift", "aliases=Kickoff, Project Start"])
}

@Test func nestedFrontMatterKeysReplaceTheirParent() {
    let md = """
    ---
    draft:
    metadata:
      node_type: memory
      type: feedback
    status: open
    ---
    """
    #expect(properties(md) == ["draft=", "metadata.node_type=memory", "metadata.type=feedback", "status=open"])
}

@Test func joinsFrontMatterContinuationLines() {
    #expect(properties("---\nsummary: first part\n  second part\n---") == ["summary=first part second part"])
}

@Test func foldsFrontMatterBlockScalars() {
    let md = """
    ---
    summary: |
      First line
      second line
    note: >-
      folded text
      continues
    ---
    """
    #expect(properties(md) == ["summary=First line second line", "note=folded text continues"])
}

@Test func blockScalarTextWithColonStaysText() {
    let md = """
    ---
    description: |
      Why: links need a target
    ---
    """
    #expect(properties(md) == ["description=Why: links need a target"])
}

@Test func skipsFrontMatterComments() {
    let md = """
    ---
    # generated by template
    title: Weekly sync
      # indented comment
    status: done
    ---
    """
    #expect(properties(md) == ["title=Weekly sync", "status=done"])
}

@Test func frontMatterClosedByDotsKeepsHeadingLine() {
    let html = MarkdownRenderer.renderHTML(from: "---\ntitle: Weekly\n...\n# Agenda")
    #expect(html == """
    <details class="frontmatter" data-line="0" open><summary>Properties</summary><table><tbody>
    <tr><th>title</th><td>Weekly</td></tr>
    </tbody></table></details>
    <h1 id="agenda" data-line="3">Agenda</h1>

    """)
}

@Test func bodyRightAfterFrontMatterKeepsItsLine() {
    let html = MarkdownRenderer.renderHTML(from: "---\ntitle: x\n---\nBody text\n\n## Next")
    #expect(html.contains("</details>\n<p data-line=\"3\">Body text</p>\n<h2 id=\"next\" data-line=\"5\">Next</h2>\n"))
}

@Test func frontMatterValuesAreLinkedAndEscaped() {
    let md = """
    ---
    related:
      - "[[Alpha Note]]"
      - "[[Beta]]"
    source: https://example.com/spec
    title: <script>alert(1)</script>
    ---
    """
    let html = MarkdownRenderer.renderHTML(from: md)
    #expect(html.contains("<tr><th>related</th><td><a class=\"wikilink\" href=\"wikilink:Alpha%20Note\">Alpha Note</a>, <a class=\"wikilink\" href=\"wikilink:Beta\">Beta</a></td></tr>"))
    #expect(html.contains("<tr><th>source</th><td><a href=\"https://example.com/spec\">https://example.com/spec</a></td></tr>"))
    #expect(html.contains("<tr><th>title</th><td>&lt;script&gt;alert(1)&lt;/script&gt;</td></tr>"))
    #expect(!html.contains("<script"))
}

@Test(arguments: [
    "---\ntitle: Draft\n\nBody",
    "---\njust a sentence\n---",
    "---\n---\n# Title",
    "\n---\ntitle: Draft\n---",
])
func notFrontMatterIsLeftToMarkdown(_ source: String) {
    #expect(FrontMatter.parse(lines: source.components(separatedBy: "\n")) == nil)
    let html = MarkdownRenderer.renderHTML(from: source)
    #expect(!html.contains("class=\"frontmatter\""))
    #expect(html.contains("<hr data-line="))
}

@Test func parsesFrontMatterWithNonLatinKeys() {
    #expect(properties("---\nназва: Звіт\nтеги:\n  - звіт\n  - Q3\n---") == ["назва=Звіт", "теги=звіт, Q3"])
}

@Test func parsesInlineFrontMatterLists() {
    let md = """
    ---
    aliases: [Foo, "Bar Baz", 'Q']
    tags: [qa, , "", swift]
    empty: []
    ---
    """
    #expect(properties(md) == ["aliases=Foo, Bar Baz, Q", "tags=qa, swift", "empty="])
}

@Test(arguments: ["|", ">", "|-", ">-", "|+", ">+"])
func blockScalarLinesStayTextUntilNextKey(_ indicator: String) {
    let md = """
    ---
    note: \(indicator)
      Why: it reads like a key
      # not a comment
      - not a list item

      after a blank line
    next: done
    ---
    """
    #expect(properties(md) == ["note=Why: it reads like a key # not a comment - not a list item after a blank line", "next=done"])
}

@Test func crlfFrontMatterIsRecognised() {
    let source = "---\r\ntitle: X\r\n---\r\n# H"
    #expect(properties(source) == ["title=X"])
    #expect(MarkdownRenderer.renderHTML(from: source) == """
    <details class="frontmatter" data-line="0" open><summary>Properties</summary><table><tbody>
    <tr><th>title</th><td>X</td></tr>
    </tbody></table></details>
    <h1 id="h" data-line="3">H</h1>

    """)
}
